plugins {
    id 'com.android.application'
}

android {
    namespace 'com.uwuh.pif'
    compileSdk 34

    defaultConfig {
        applicationId "com.uwuh.pif"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Kosong - Murni memakai framework bawaan ROM
    // JSON parsing pakai org.json (sudah ada di Android)
}
