plugins {
    id 'com.android.application'
}

android {
    namespace 'com.uwuh.pif'
    compileSdk 34

    defaultConfig {
        applicationId "com.uwuh.pif"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Tambahkan library startup agar kelas InitializationProvider ditemukan
    implementation 'androidx.startup:startup-runtime:1.1.1'
}
